# Generated by Django 3.1.1 on 2020-09-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=25)),
                ('age', models.IntegerField(null=True)),
                ('breed', models.CharField(max_length=200)),
                ('born', models.CharField(blank=True, max_length=50, null=True, verbose_name='Date of birth')),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('lifespan', models.IntegerField(null=True)),
                ('temperament', models.CharField(max_length=100)),
                ('had_owner', models.BooleanField(blank=True, default=False, null=True)),
                ('animal_sex', models.CharField(max_length=20)),
                ('profile_link', models.CharField(max_length=300)),
                ('profile_photo_link', models.CharField(max_length=300)),
                ('animal_description', models.CharField(max_length=500)),
                ('asylum', models.CharField(max_length=300)),
                ('contact_string', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['animal_name'],
            },
        ),
    ]
