# Generated by Django 3.1.1 on 2020-09-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_sex',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='temperament',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
