# Generated by Django 3.1.1 on 2020-09-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_aggregator', '0002_auto_20200927_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='contact_string',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
